// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

/*
Package model is a generated protocol buffer package.

It is generated from these files:
	model.proto

It has these top-level messages:
	CompletionResult
	BlobDatum
	HttpHeader
	HttpReqDatum
	HttpRespDatum
	EmptyDatum
	StageRefDatum
	ErrorDatum
	Datum
	AddChainedStageRequest
	AddCompletedValueStageRequest
	AddDelayStageRequest
	AddExternalCompletionStageRequest
	AddInvokeFunctionStageRequest
	AddStageResponse
	CommitGraphRequest
	CommitGraphProcessed
	CompleteDelayStageRequest
	CompleteStageExternallyRequest
	CompleteStageExternallyResponse
	DeactivateGraphRequest
	CreateGraphRequest
	CreateGraphResponse
	FaasInvocationResponse
	GetGraphStateRequest
	GetGraphStateResponse
	ListGraphsRequest
	ListGraphResponse
	ListGraphsResponse
	GetStageResultRequest
	GetStageResultResponse
	InvalidGraphOperation
	InvalidStageOperation
	InvokeFunctionRequest
	InvokeStageRequest
	DelayScheduledEvent
	GraphCreatedEvent
	GraphCompletedEvent
	GraphCommittedEvent
	StageAddedEvent
	StageCompletedEvent
	StageComposedEvent
	FaasInvocationStartedEvent
	FaasInvocationCompletedEvent
*/
package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HttpMethod int32

const (
	HttpMethod_unknown_method HttpMethod = 0
	HttpMethod_get            HttpMethod = 1
	HttpMethod_head           HttpMethod = 2
	HttpMethod_post           HttpMethod = 3
	HttpMethod_put            HttpMethod = 4
	HttpMethod_delete         HttpMethod = 5
	HttpMethod_options        HttpMethod = 7
	HttpMethod_patch          HttpMethod = 6
)

var HttpMethod_name = map[int32]string{
	0: "unknown_method",
	1: "get",
	2: "head",
	3: "post",
	4: "put",
	5: "delete",
	7: "options",
	6: "patch",
}
var HttpMethod_value = map[string]int32{
	"unknown_method": 0,
	"get":            1,
	"head":           2,
	"post":           3,
	"put":            4,
	"delete":         5,
	"options":        7,
	"patch":          6,
}

func (x HttpMethod) String() string {
	return proto.EnumName(HttpMethod_name, int32(x))
}
func (HttpMethod) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ErrorDatumType int32

const (
	ErrorDatumType_unknown_error          ErrorDatumType = 0
	ErrorDatumType_stage_timeout          ErrorDatumType = 1
	ErrorDatumType_stage_failed           ErrorDatumType = 2
	ErrorDatumType_function_timeout       ErrorDatumType = 3
	ErrorDatumType_function_invoke_failed ErrorDatumType = 4
	ErrorDatumType_stage_lost             ErrorDatumType = 5
	ErrorDatumType_invalid_stage_response ErrorDatumType = 6
)

var ErrorDatumType_name = map[int32]string{
	0: "unknown_error",
	1: "stage_timeout",
	2: "stage_failed",
	3: "function_timeout",
	4: "function_invoke_failed",
	5: "stage_lost",
	6: "invalid_stage_response",
}
var ErrorDatumType_value = map[string]int32{
	"unknown_error":          0,
	"stage_timeout":          1,
	"stage_failed":           2,
	"function_timeout":       3,
	"function_invoke_failed": 4,
	"stage_lost":             5,
	"invalid_stage_response": 6,
}

func (x ErrorDatumType) String() string {
	return proto.EnumName(ErrorDatumType_name, int32(x))
}
func (ErrorDatumType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type CompletionOperation int32

const (
	CompletionOperation_unknown_operation  CompletionOperation = 0
	CompletionOperation_acceptEither       CompletionOperation = 1
	CompletionOperation_applyToEither      CompletionOperation = 2
	CompletionOperation_thenAcceptBoth     CompletionOperation = 3
	CompletionOperation_thenApply          CompletionOperation = 4
	CompletionOperation_thenRun            CompletionOperation = 5
	CompletionOperation_thenAccept         CompletionOperation = 6
	CompletionOperation_thenCompose        CompletionOperation = 7
	CompletionOperation_thenCombine        CompletionOperation = 8
	CompletionOperation_whenComplete       CompletionOperation = 9
	CompletionOperation_handle             CompletionOperation = 10
	CompletionOperation_supply             CompletionOperation = 11
	CompletionOperation_invokeFunction     CompletionOperation = 12
	CompletionOperation_completedValue     CompletionOperation = 13
	CompletionOperation_delay              CompletionOperation = 14
	CompletionOperation_allOf              CompletionOperation = 15
	CompletionOperation_anyOf              CompletionOperation = 16
	CompletionOperation_externalCompletion CompletionOperation = 17
	CompletionOperation_exceptionally      CompletionOperation = 18
)

var CompletionOperation_name = map[int32]string{
	0:  "unknown_operation",
	1:  "acceptEither",
	2:  "applyToEither",
	3:  "thenAcceptBoth",
	4:  "thenApply",
	5:  "thenRun",
	6:  "thenAccept",
	7:  "thenCompose",
	8:  "thenCombine",
	9:  "whenComplete",
	10: "handle",
	11: "supply",
	12: "invokeFunction",
	13: "completedValue",
	14: "delay",
	15: "allOf",
	16: "anyOf",
	17: "externalCompletion",
	18: "exceptionally",
}
var CompletionOperation_value = map[string]int32{
	"unknown_operation":  0,
	"acceptEither":       1,
	"applyToEither":      2,
	"thenAcceptBoth":     3,
	"thenApply":          4,
	"thenRun":            5,
	"thenAccept":         6,
	"thenCompose":        7,
	"thenCombine":        8,
	"whenComplete":       9,
	"handle":             10,
	"supply":             11,
	"invokeFunction":     12,
	"completedValue":     13,
	"delay":              14,
	"allOf":              15,
	"anyOf":              16,
	"externalCompletion": 17,
	"exceptionally":      18,
}

func (x CompletionOperation) String() string {
	return proto.EnumName(CompletionOperation_name, int32(x))
}
func (CompletionOperation) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ListGraphsFilter int32

const (
	ListGraphsFilter_unknown   ListGraphsFilter = 0
	ListGraphsFilter_all       ListGraphsFilter = 1
	ListGraphsFilter_running   ListGraphsFilter = 2
	ListGraphsFilter_completed ListGraphsFilter = 3
)

var ListGraphsFilter_name = map[int32]string{
	0: "unknown",
	1: "all",
	2: "running",
	3: "completed",
}
var ListGraphsFilter_value = map[string]int32{
	"unknown":   0,
	"all":       1,
	"running":   2,
	"completed": 3,
}

func (x ListGraphsFilter) String() string {
	return proto.EnumName(ListGraphsFilter_name, int32(x))
}
func (ListGraphsFilter) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type CompletionResult struct {
	Successful bool   `protobuf:"varint,1,opt,name=successful" json:"successful,omitempty"`
	Datum      *Datum `protobuf:"bytes,2,opt,name=datum" json:"datum,omitempty"`
}

func (m *CompletionResult) Reset()                    { *m = CompletionResult{} }
func (m *CompletionResult) String() string            { return proto.CompactTextString(m) }
func (*CompletionResult) ProtoMessage()               {}
func (*CompletionResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CompletionResult) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

func (m *CompletionResult) GetDatum() *Datum {
	if m != nil {
		return m.Datum
	}
	return nil
}

type BlobDatum struct {
	BlobId      string `protobuf:"bytes,1,opt,name=blob_id,json=blobId" json:"blob_id,omitempty"`
	ContentType string `protobuf:"bytes,2,opt,name=content_type,json=contentType" json:"content_type,omitempty"`
	Length      uint64 `protobuf:"varint,3,opt,name=length" json:"length,omitempty"`
}

func (m *BlobDatum) Reset()                    { *m = BlobDatum{} }
func (m *BlobDatum) String() string            { return proto.CompactTextString(m) }
func (*BlobDatum) ProtoMessage()               {}
func (*BlobDatum) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BlobDatum) GetBlobId() string {
	if m != nil {
		return m.BlobId
	}
	return ""
}

func (m *BlobDatum) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *BlobDatum) GetLength() uint64 {
	if m != nil {
		return m.Length
	}
	return 0
}

type HttpHeader struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *HttpHeader) Reset()                    { *m = HttpHeader{} }
func (m *HttpHeader) String() string            { return proto.CompactTextString(m) }
func (*HttpHeader) ProtoMessage()               {}
func (*HttpHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *HttpHeader) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *HttpHeader) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type HttpReqDatum struct {
	Body    *BlobDatum    `protobuf:"bytes,1,opt,name=body" json:"body,omitempty"`
	Headers []*HttpHeader `protobuf:"bytes,3,rep,name=headers" json:"headers,omitempty"`
	Method  HttpMethod    `protobuf:"varint,4,opt,name=method,enum=model.HttpMethod" json:"method,omitempty"`
}

func (m *HttpReqDatum) Reset()                    { *m = HttpReqDatum{} }
func (m *HttpReqDatum) String() string            { return proto.CompactTextString(m) }
func (*HttpReqDatum) ProtoMessage()               {}
func (*HttpReqDatum) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *HttpReqDatum) GetBody() *BlobDatum {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *HttpReqDatum) GetHeaders() []*HttpHeader {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *HttpReqDatum) GetMethod() HttpMethod {
	if m != nil {
		return m.Method
	}
	return HttpMethod_unknown_method
}

type HttpRespDatum struct {
	Body       *BlobDatum    `protobuf:"bytes,1,opt,name=body" json:"body,omitempty"`
	Headers    []*HttpHeader `protobuf:"bytes,3,rep,name=headers" json:"headers,omitempty"`
	StatusCode uint32        `protobuf:"varint,4,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
}

func (m *HttpRespDatum) Reset()                    { *m = HttpRespDatum{} }
func (m *HttpRespDatum) String() string            { return proto.CompactTextString(m) }
func (*HttpRespDatum) ProtoMessage()               {}
func (*HttpRespDatum) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *HttpRespDatum) GetBody() *BlobDatum {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *HttpRespDatum) GetHeaders() []*HttpHeader {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *HttpRespDatum) GetStatusCode() uint32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

type EmptyDatum struct {
}

func (m *EmptyDatum) Reset()                    { *m = EmptyDatum{} }
func (m *EmptyDatum) String() string            { return proto.CompactTextString(m) }
func (*EmptyDatum) ProtoMessage()               {}
func (*EmptyDatum) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type StageRefDatum struct {
	StageRef string `protobuf:"bytes,1,opt,name=stage_ref,json=stageRef" json:"stage_ref,omitempty"`
}

func (m *StageRefDatum) Reset()                    { *m = StageRefDatum{} }
func (m *StageRefDatum) String() string            { return proto.CompactTextString(m) }
func (*StageRefDatum) ProtoMessage()               {}
func (*StageRefDatum) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *StageRefDatum) GetStageRef() string {
	if m != nil {
		return m.StageRef
	}
	return ""
}

type ErrorDatum struct {
	Type    ErrorDatumType `protobuf:"varint,1,opt,name=type,enum=model.ErrorDatumType" json:"type,omitempty"`
	Message string         `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *ErrorDatum) Reset()                    { *m = ErrorDatum{} }
func (m *ErrorDatum) String() string            { return proto.CompactTextString(m) }
func (*ErrorDatum) ProtoMessage()               {}
func (*ErrorDatum) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ErrorDatum) GetType() ErrorDatumType {
	if m != nil {
		return m.Type
	}
	return ErrorDatumType_unknown_error
}

func (m *ErrorDatum) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Datum struct {
	// Types that are valid to be assigned to Val:
	//	*Datum_Empty
	//	*Datum_Blob
	//	*Datum_Error
	//	*Datum_StageRef
	//	*Datum_HttpReq
	//	*Datum_HttpResp
	Val isDatum_Val `protobuf_oneof:"val"`
}

func (m *Datum) Reset()                    { *m = Datum{} }
func (m *Datum) String() string            { return proto.CompactTextString(m) }
func (*Datum) ProtoMessage()               {}
func (*Datum) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type isDatum_Val interface {
	isDatum_Val()
}

type Datum_Empty struct {
	Empty *EmptyDatum `protobuf:"bytes,1,opt,name=empty,oneof"`
}
type Datum_Blob struct {
	Blob *BlobDatum `protobuf:"bytes,2,opt,name=blob,oneof"`
}
type Datum_Error struct {
	Error *ErrorDatum `protobuf:"bytes,3,opt,name=error,oneof"`
}
type Datum_StageRef struct {
	StageRef *StageRefDatum `protobuf:"bytes,4,opt,name=stage_ref,json=stageRef,oneof"`
}
type Datum_HttpReq struct {
	HttpReq *HttpReqDatum `protobuf:"bytes,5,opt,name=http_req,json=httpReq,oneof"`
}
type Datum_HttpResp struct {
	HttpResp *HttpRespDatum `protobuf:"bytes,6,opt,name=http_resp,json=httpResp,oneof"`
}

func (*Datum_Empty) isDatum_Val()    {}
func (*Datum_Blob) isDatum_Val()     {}
func (*Datum_Error) isDatum_Val()    {}
func (*Datum_StageRef) isDatum_Val() {}
func (*Datum_HttpReq) isDatum_Val()  {}
func (*Datum_HttpResp) isDatum_Val() {}

func (m *Datum) GetVal() isDatum_Val {
	if m != nil {
		return m.Val
	}
	return nil
}

func (m *Datum) GetEmpty() *EmptyDatum {
	if x, ok := m.GetVal().(*Datum_Empty); ok {
		return x.Empty
	}
	return nil
}

func (m *Datum) GetBlob() *BlobDatum {
	if x, ok := m.GetVal().(*Datum_Blob); ok {
		return x.Blob
	}
	return nil
}

func (m *Datum) GetError() *ErrorDatum {
	if x, ok := m.GetVal().(*Datum_Error); ok {
		return x.Error
	}
	return nil
}

func (m *Datum) GetStageRef() *StageRefDatum {
	if x, ok := m.GetVal().(*Datum_StageRef); ok {
		return x.StageRef
	}
	return nil
}

func (m *Datum) GetHttpReq() *HttpReqDatum {
	if x, ok := m.GetVal().(*Datum_HttpReq); ok {
		return x.HttpReq
	}
	return nil
}

func (m *Datum) GetHttpResp() *HttpRespDatum {
	if x, ok := m.GetVal().(*Datum_HttpResp); ok {
		return x.HttpResp
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Datum) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Datum_OneofMarshaler, _Datum_OneofUnmarshaler, _Datum_OneofSizer, []interface{}{
		(*Datum_Empty)(nil),
		(*Datum_Blob)(nil),
		(*Datum_Error)(nil),
		(*Datum_StageRef)(nil),
		(*Datum_HttpReq)(nil),
		(*Datum_HttpResp)(nil),
	}
}

func _Datum_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Datum)
	// val
	switch x := m.Val.(type) {
	case *Datum_Empty:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Empty); err != nil {
			return err
		}
	case *Datum_Blob:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Blob); err != nil {
			return err
		}
	case *Datum_Error:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Error); err != nil {
			return err
		}
	case *Datum_StageRef:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.StageRef); err != nil {
			return err
		}
	case *Datum_HttpReq:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.HttpReq); err != nil {
			return err
		}
	case *Datum_HttpResp:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.HttpResp); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Datum.Val has unexpected type %T", x)
	}
	return nil
}

func _Datum_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Datum)
	switch tag {
	case 1: // val.empty
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(EmptyDatum)
		err := b.DecodeMessage(msg)
		m.Val = &Datum_Empty{msg}
		return true, err
	case 2: // val.blob
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BlobDatum)
		err := b.DecodeMessage(msg)
		m.Val = &Datum_Blob{msg}
		return true, err
	case 3: // val.error
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ErrorDatum)
		err := b.DecodeMessage(msg)
		m.Val = &Datum_Error{msg}
		return true, err
	case 4: // val.stage_ref
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(StageRefDatum)
		err := b.DecodeMessage(msg)
		m.Val = &Datum_StageRef{msg}
		return true, err
	case 5: // val.http_req
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HttpReqDatum)
		err := b.DecodeMessage(msg)
		m.Val = &Datum_HttpReq{msg}
		return true, err
	case 6: // val.http_resp
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HttpRespDatum)
		err := b.DecodeMessage(msg)
		m.Val = &Datum_HttpResp{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Datum_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Datum)
	// val
	switch x := m.Val.(type) {
	case *Datum_Empty:
		s := proto.Size(x.Empty)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Datum_Blob:
		s := proto.Size(x.Blob)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Datum_Error:
		s := proto.Size(x.Error)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Datum_StageRef:
		s := proto.Size(x.StageRef)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Datum_HttpReq:
		s := proto.Size(x.HttpReq)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Datum_HttpResp:
		s := proto.Size(x.HttpResp)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Commands
type AddChainedStageRequest struct {
	// the graph this stage belongs to
	GraphId string `protobuf:"bytes,1,opt,name=graph_id,json=graphId" json:"graph_id,omitempty"`
	// the completion operation for this stage
	Operation CompletionOperation `protobuf:"varint,2,opt,name=operation,enum=model.CompletionOperation" json:"operation,omitempty"`
	// the (optional) closure associated with this stage
	Closure *BlobDatum `protobuf:"bytes,3,opt,name=closure" json:"closure,omitempty"`
	// the ids of the nodes that this stage depends on if any
	Deps []string `protobuf:"bytes,4,rep,name=deps" json:"deps,omitempty"`
	// The node that created this stage this is optional
	CreatorId string `protobuf:"bytes,5,opt,name=creator_id,json=creatorId" json:"creator_id,omitempty"`
}

func (m *AddChainedStageRequest) Reset()                    { *m = AddChainedStageRequest{} }
func (m *AddChainedStageRequest) String() string            { return proto.CompactTextString(m) }
func (*AddChainedStageRequest) ProtoMessage()               {}
func (*AddChainedStageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *AddChainedStageRequest) GetGraphId() string {
	if m != nil {
		return m.GraphId
	}
	return ""
}

func (m *AddChainedStageRequest) GetOperation() CompletionOperation {
	if m != nil {
		return m.Operation
	}
	return CompletionOperation_unknown_operation
}

func (m *AddChainedStageRequest) GetClosure() *BlobDatum {
	if m != nil {
		return m.Closure
	}
	return nil
}

func (m *AddChainedStageRequest) GetDeps() []string {
	if m != nil {
		return m.Deps
	}
	return nil
}

func (m *AddChainedStageRequest) GetCreatorId() string {
	if m != nil {
		return m.CreatorId
	}
	return ""
}

type AddCompletedValueStageRequest struct {
	GraphId   string            `protobuf:"bytes,1,opt,name=graph_id,json=graphId" json:"graph_id,omitempty"`
	Result    *CompletionResult `protobuf:"bytes,2,opt,name=result" json:"result,omitempty"`
	CreatorId string            `protobuf:"bytes,3,opt,name=creator_id,json=creatorId" json:"creator_id,omitempty"`
}

func (m *AddCompletedValueStageRequest) Reset()                    { *m = AddCompletedValueStageRequest{} }
func (m *AddCompletedValueStageRequest) String() string            { return proto.CompactTextString(m) }
func (*AddCompletedValueStageRequest) ProtoMessage()               {}
func (*AddCompletedValueStageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *AddCompletedValueStageRequest) GetGraphId() string {
	if m != nil {
		return m.GraphId
	}
	return ""
}

func (m *AddCompletedValueStageRequest) GetResult() *CompletionResult {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *AddCompletedValueStageRequest) GetCreatorId() string {
	if m != nil {
		return m.CreatorId
	}
	return ""
}

type AddDelayStageRequest struct {
	GraphId   string `protobuf:"bytes,1,opt,name=graph_id,json=graphId" json:"graph_id,omitempty"`
	DelayMs   int64  `protobuf:"varint,2,opt,name=delay_ms,json=delayMs" json:"delay_ms,omitempty"`
	CreatorId string `protobuf:"bytes,3,opt,name=creator_id,json=creatorId" json:"creator_id,omitempty"`
}

func (m *AddDelayStageRequest) Reset()                    { *m = AddDelayStageRequest{} }
func (m *AddDelayStageRequest) String() string            { return proto.CompactTextString(m) }
func (*AddDelayStageRequest) ProtoMessage()               {}
func (*AddDelayStageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *AddDelayStageRequest) GetGraphId() string {
	if m != nil {
		return m.GraphId
	}
	return ""
}

func (m *AddDelayStageRequest) GetDelayMs() int64 {
	if m != nil {
		return m.DelayMs
	}
	return 0
}

func (m *AddDelayStageRequest) GetCreatorId() string {
	if m != nil {
		return m.CreatorId
	}
	return ""
}

type AddExternalCompletionStageRequest struct {
	GraphId   string `protobuf:"bytes,1,opt,name=graph_id,json=graphId" json:"graph_id,omitempty"`
	CreatorId string `protobuf:"bytes,2,opt,name=creator_id,json=creatorId" json:"creator_id,omitempty"`
}

func (m *AddExternalCompletionStageRequest) Reset()         { *m = AddExternalCompletionStageRequest{} }
func (m *AddExternalCompletionStageRequest) String() string { return proto.CompactTextString(m) }
func (*AddExternalCompletionStageRequest) ProtoMessage()    {}
func (*AddExternalCompletionStageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{12}
}

func (m *AddExternalCompletionStageRequest) GetGraphId() string {
	if m != nil {
		return m.GraphId
	}
	return ""
}

func (m *AddExternalCompletionStageRequest) GetCreatorId() string {
	if m != nil {
		return m.CreatorId
	}
	return ""
}

type AddInvokeFunctionStageRequest struct {
	GraphId    string        `protobuf:"bytes,1,opt,name=graph_id,json=graphId" json:"graph_id,omitempty"`
	FunctionId string        `protobuf:"bytes,2,opt,name=function_id,json=functionId" json:"function_id,omitempty"`
	Arg        *HttpReqDatum `protobuf:"bytes,3,opt,name=arg" json:"arg,omitempty"`
	CreatorId  string        `protobuf:"bytes,4,opt,name=creator_id,json=creatorId" json:"creator_id,omitempty"`
}

func (m *AddInvokeFunctionStageRequest) Reset()                    { *m = AddInvokeFunctionStageRequest{} }
func (m *AddInvokeFunctionStageRequest) String() string            { return proto.CompactTextString(m) }
func (*AddInvokeFunctionStageRequest) ProtoMessage()               {}
func (*AddInvokeFunctionStageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *AddInvokeFunctionStageRequest) GetGraphId() string {
	if m != nil {
		return m.GraphId
	}
	return ""
}

func (m *AddInvokeFunctionStageRequest) GetFunctionId() string {
	if m != nil {
		return m.FunctionId
	}
	return ""
}

func (m *AddInvokeFunctionStageRequest) GetArg() *HttpReqDatum {
	if m != nil {
		return m.Arg
	}
	return nil
}

func (m *AddInvokeFunctionStageRequest) GetCreatorId() string {
	if m != nil {
		return m.CreatorId
	}
	return ""
}

type AddStageResponse struct {
	GraphId string `protobuf:"bytes,1,opt,name=graph_id,json=graphId" json:"graph_id,omitempty"`
	StageId string `protobuf:"bytes,2,opt,name=stage_id,json=stageId" json:"stage_id,omitempty"`
}

func (m *AddStageResponse) Reset()                    { *m = AddStageResponse{} }
func (m *AddStageResponse) String() string            { return proto.CompactTextString(m) }
func (*AddStageResponse) ProtoMessage()               {}
func (*AddStageResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *AddStageResponse) GetGraphId() string {
	if m != nil {
		return m.GraphId
	}
	return ""
}

func (m *AddStageResponse) GetStageId() string {
	if m != nil {
		return m.StageId
	}
	return ""
}

type CommitGraphRequest struct {
	GraphId string `protobuf:"bytes,1,opt,name=graph_id,json=graphId" json:"graph_id,omitempty"`
}

func (m *CommitGraphRequest) Reset()                    { *m = CommitGraphRequest{} }
func (m *CommitGraphRequest) String() string            { return proto.CompactTextString(m) }
func (*CommitGraphRequest) ProtoMessage()               {}
func (*CommitGraphRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *CommitGraphRequest) GetGraphId() string {
	if m != nil {
		return m.GraphId
	}
	return ""
}

type CommitGraphProcessed struct {
	GraphId string `protobuf:"bytes,1,opt,name=graph_id,json=graphId" json:"graph_id,omitempty"`
}

func (m *CommitGraphProcessed) Reset()                    { *m = CommitGraphProcessed{} }
func (m *CommitGraphProcessed) String() string            { return proto.CompactTextString(m) }
func (*CommitGraphProcessed) ProtoMessage()               {}
func (*CommitGraphProcessed) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *CommitGraphProcessed) GetGraphId() string {
	if m != nil {
		return m.GraphId
	}
	return ""
}

type CompleteDelayStageRequest struct {
	GraphId string            `protobuf:"bytes,1,opt,name=graph_id,json=graphId" json:"graph_id,omitempty"`
	StageId string            `protobuf:"bytes,2,opt,name=stage_id,json=stageId" json:"stage_id,omitempty"`
	Result  *CompletionResult `protobuf:"bytes,3,opt,name=result" json:"result,omitempty"`
}

func (m *CompleteDelayStageRequest) Reset()                    { *m = CompleteDelayStageRequest{} }
func (m *CompleteDelayStageRequest) String() string            { return proto.CompactTextString(m) }
func (*CompleteDelayStageRequest) ProtoMessage()               {}
func (*CompleteDelayStageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *CompleteDelayStageRequest) GetGraphId() string {
	if m != nil {
		return m.GraphId
	}
	return ""
}

func (m *CompleteDelayStageRequest) GetStageId() string {
	if m != nil {
		return m.StageId
	}
	return ""
}

func (m *CompleteDelayStageRequest) GetResult() *CompletionResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type CompleteStageExternallyRequest struct {
	GraphId string            `protobuf:"bytes,1,opt,name=graph_id,json=graphId" json:"graph_id,omitempty"`
	StageId string            `protobuf:"bytes,2,opt,name=stage_id,json=stageId" json:"stage_id,omitempty"`
	Result  *CompletionResult `protobuf:"bytes,3,opt,name=result" json:"result,omitempty"`
}

func (m *CompleteStageExternallyRequest) Reset()                    { *m = CompleteStageExternallyRequest{} }
func (m *CompleteStageExternallyRequest) String() string            { return proto.CompactTextString(m) }
func (*CompleteStageExternallyRequest) ProtoMessage()               {}
func (*CompleteStageExternallyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *CompleteStageExternallyRequest) GetGraphId() string {
	if m != nil {
		return m.GraphId
	}
	return ""
}

func (m *CompleteStageExternallyRequest) GetStageId() string {
	if m != nil {
		return m.StageId
	}
	return ""
}

func (m *CompleteStageExternallyRequest) GetResult() *CompletionResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type CompleteStageExternallyResponse struct {
	GraphId    string `protobuf:"bytes,1,opt,name=graph_id,json=graphId" json:"graph_id,omitempty"`
	StageId    string `protobuf:"bytes,2,opt,name=stage_id,json=stageId" json:"stage_id,omitempty"`
	Successful bool   `protobuf:"varint,3,opt,name=successful" json:"successful,omitempty"`
}

func (m *CompleteStageExternallyResponse) Reset()         { *m = CompleteStageExternallyResponse{} }
func (m *CompleteStageExternallyResponse) String() string { return proto.CompactTextString(m) }
func (*CompleteStageExternallyResponse) ProtoMessage()    {}
func (*CompleteStageExternallyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{19}
}

func (m *CompleteStageExternallyResponse) GetGraphId() string {
	if m != nil {
		return m.GraphId
	}
	return ""
}

func (m *CompleteStageExternallyResponse) GetStageId() string {
	if m != nil {
		return m.StageId
	}
	return ""
}

func (m *CompleteStageExternallyResponse) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

type DeactivateGraphRequest struct {
	GraphId string `protobuf:"bytes,1,opt,name=graph_id,json=graphId" json:"graph_id,omitempty"`
}

func (m *DeactivateGraphRequest) Reset()                    { *m = DeactivateGraphRequest{} }
func (m *DeactivateGraphRequest) String() string            { return proto.CompactTextString(m) }
func (*DeactivateGraphRequest) ProtoMessage()               {}
func (*DeactivateGraphRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *DeactivateGraphRequest) GetGraphId() string {
	if m != nil {
		return m.GraphId
	}
	return ""
}

type CreateGraphRequest struct {
	FunctionId string `protobuf:"bytes,1,opt,name=function_id,json=functionId" json:"function_id,omitempty"`
	GraphId    string `protobuf:"bytes,2,opt,name=graph_id,json=graphId" json:"graph_id,omitempty"`
}

func (m *CreateGraphRequest) Reset()                    { *m = CreateGraphRequest{} }
func (m *CreateGraphRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateGraphRequest) ProtoMessage()               {}
func (*CreateGraphRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *CreateGraphRequest) GetFunctionId() string {
	if m != nil {
		return m.FunctionId
	}
	return ""
}

func (m *CreateGraphRequest) GetGraphId() string {
	if m != nil {
		return m.GraphId
	}
	return ""
}

type CreateGraphResponse struct {
	GraphId string `protobuf:"bytes,1,opt,name=graph_id,json=graphId" json:"graph_id,omitempty"`
}

func (m *CreateGraphResponse) Reset()                    { *m = CreateGraphResponse{} }
func (m *CreateGraphResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateGraphResponse) ProtoMessage()               {}
func (*CreateGraphResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *CreateGraphResponse) GetGraphId() string {
	if m != nil {
		return m.GraphId
	}
	return ""
}

type FaasInvocationResponse struct {
	GraphId    string            `protobuf:"bytes,1,opt,name=graph_id,json=graphId" json:"graph_id,omitempty"`
	StageId    string            `protobuf:"bytes,2,opt,name=stage_id,json=stageId" json:"stage_id,omitempty"`
	FunctionId string            `protobuf:"bytes,3,opt,name=function_id,json=functionId" json:"function_id,omitempty"`
	Result     *CompletionResult `protobuf:"bytes,4,opt,name=result" json:"result,omitempty"`
}

func (m *FaasInvocationResponse) Reset()                    { *m = FaasInvocationResponse{} }
func (m *FaasInvocationResponse) String() string            { return proto.CompactTextString(m) }
func (*FaasInvocationResponse) ProtoMessage()               {}
func (*FaasInvocationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *FaasInvocationResponse) GetGraphId() string {
	if m != nil {
		return m.GraphId
	}
	return ""
}

func (m *FaasInvocationResponse) GetStageId() string {
	if m != nil {
		return m.StageId
	}
	return ""
}

func (m *FaasInvocationResponse) GetFunctionId() string {
	if m != nil {
		return m.FunctionId
	}
	return ""
}

func (m *FaasInvocationResponse) GetResult() *CompletionResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type GetGraphStateRequest struct {
	GraphId string `protobuf:"bytes,1,opt,name=graph_id,json=graphId" json:"graph_id,omitempty"`
}

func (m *GetGraphStateRequest) Reset()                    { *m = GetGraphStateRequest{} }
func (m *GetGraphStateRequest) String() string            { return proto.CompactTextString(m) }
func (*GetGraphStateRequest) ProtoMessage()               {}
func (*GetGraphStateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *GetGraphStateRequest) GetGraphId() string {
	if m != nil {
		return m.GraphId
	}
	return ""
}

type GetGraphStateResponse struct {
	Stages     map[string]*GetGraphStateResponse_StageRepresentation `protobuf:"bytes,1,rep,name=stages" json:"stages,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FunctionId string                                                `protobuf:"bytes,2,opt,name=function_id,json=functionId" json:"function_id,omitempty"`
	GraphId    string                                                `protobuf:"bytes,3,opt,name=graph_id,json=graphId" json:"graph_id,omitempty"`
}

func (m *GetGraphStateResponse) Reset()                    { *m = GetGraphStateResponse{} }
func (m *GetGraphStateResponse) String() string            { return proto.CompactTextString(m) }
func (*GetGraphStateResponse) ProtoMessage()               {}
func (*GetGraphStateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *GetGraphStateResponse) GetStages() map[string]*GetGraphStateResponse_StageRepresentation {
	if m != nil {
		return m.Stages
	}
	return nil
}

func (m *GetGraphStateResponse) GetFunctionId() string {
	if m != nil {
		return m.FunctionId
	}
	return ""
}

func (m *GetGraphStateResponse) GetGraphId() string {
	if m != nil {
		return m.GraphId
	}
	return ""
}

type GetGraphStateResponse_StageRepresentation struct {
	Type         string   `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Status       string   `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
	Dependencies []string `protobuf:"bytes,3,rep,name=dependencies" json:"dependencies,omitempty"`
}

func (m *GetGraphStateResponse_StageRepresentation) Reset() {
	*m = GetGraphStateResponse_StageRepresentation{}
}
func (m *GetGraphStateResponse_StageRepresentation) String() string { return proto.CompactTextString(m) }
func (*GetGraphStateResponse_StageRepresentation) ProtoMessage()    {}
func (*GetGraphStateResponse_StageRepresentation) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{25, 0}
}

func (m *GetGraphStateResponse_StageRepresentation) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GetGraphStateResponse_StageRepresentation) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetGraphStateResponse_StageRepresentation) GetDependencies() []string {
	if m != nil {
		return m.Dependencies
	}
	return nil
}

type ListGraphsRequest struct {
	Filter ListGraphsFilter `protobuf:"varint,1,opt,name=filter,enum=model.ListGraphsFilter" json:"filter,omitempty"`
}

func (m *ListGraphsRequest) Reset()                    { *m = ListGraphsRequest{} }
func (m *ListGraphsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListGraphsRequest) ProtoMessage()               {}
func (*ListGraphsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *ListGraphsRequest) GetFilter() ListGraphsFilter {
	if m != nil {
		return m.Filter
	}
	return ListGraphsFilter_unknown
}

type ListGraphResponse struct {
	GraphId string `protobuf:"bytes,1,opt,name=graph_id,json=graphId" json:"graph_id,omitempty"`
}

func (m *ListGraphResponse) Reset()                    { *m = ListGraphResponse{} }
func (m *ListGraphResponse) String() string            { return proto.CompactTextString(m) }
func (*ListGraphResponse) ProtoMessage()               {}
func (*ListGraphResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *ListGraphResponse) GetGraphId() string {
	if m != nil {
		return m.GraphId
	}
	return ""
}

type ListGraphsResponse struct {
	Graphs []*ListGraphResponse `protobuf:"bytes,1,rep,name=graphs" json:"graphs,omitempty"`
}

func (m *ListGraphsResponse) Reset()                    { *m = ListGraphsResponse{} }
func (m *ListGraphsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListGraphsResponse) ProtoMessage()               {}
func (*ListGraphsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *ListGraphsResponse) GetGraphs() []*ListGraphResponse {
	if m != nil {
		return m.Graphs
	}
	return nil
}

type GetStageResultRequest struct {
	GraphId string `protobuf:"bytes,1,opt,name=graph_id,json=graphId" json:"graph_id,omitempty"`
	StageId string `protobuf:"bytes,2,opt,name=stage_id,json=stageId" json:"stage_id,omitempty"`
}

func (m *GetStageResultRequest) Reset()                    { *m = GetStageResultRequest{} }
func (m *GetStageResultRequest) String() string            { return proto.CompactTextString(m) }
func (*GetStageResultRequest) ProtoMessage()               {}
func (*GetStageResultRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *GetStageResultRequest) GetGraphId() string {
	if m != nil {
		return m.GraphId
	}
	return ""
}

func (m *GetStageResultRequest) GetStageId() string {
	if m != nil {
		return m.StageId
	}
	return ""
}

type GetStageResultResponse struct {
	GraphId string            `protobuf:"bytes,1,opt,name=graph_id,json=graphId" json:"graph_id,omitempty"`
	StageId string            `protobuf:"bytes,2,opt,name=stage_id,json=stageId" json:"stage_id,omitempty"`
	Result  *CompletionResult `protobuf:"bytes,3,opt,name=result" json:"result,omitempty"`
}

func (m *GetStageResultResponse) Reset()                    { *m = GetStageResultResponse{} }
func (m *GetStageResultResponse) String() string            { return proto.CompactTextString(m) }
func (*GetStageResultResponse) ProtoMessage()               {}
func (*GetStageResultResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *GetStageResultResponse) GetGraphId() string {
	if m != nil {
		return m.GraphId
	}
	return ""
}

func (m *GetStageResultResponse) GetStageId() string {
	if m != nil {
		return m.StageId
	}
	return ""
}

func (m *GetStageResultResponse) GetResult() *CompletionResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type InvalidGraphOperation struct {
	GraphId string `protobuf:"bytes,1,opt,name=graph_id,json=graphId" json:"graph_id,omitempty"`
	Err     string `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
}

func (m *InvalidGraphOperation) Reset()                    { *m = InvalidGraphOperation{} }
func (m *InvalidGraphOperation) String() string            { return proto.CompactTextString(m) }
func (*InvalidGraphOperation) ProtoMessage()               {}
func (*InvalidGraphOperation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *InvalidGraphOperation) GetGraphId() string {
	if m != nil {
		return m.GraphId
	}
	return ""
}

func (m *InvalidGraphOperation) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type InvalidStageOperation struct {
	GraphId string `protobuf:"bytes,1,opt,name=graph_id,json=graphId" json:"graph_id,omitempty"`
	Err     string `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	StageId string `protobuf:"bytes,3,opt,name=stage_id,json=stageId" json:"stage_id,omitempty"`
}

func (m *InvalidStageOperation) Reset()                    { *m = InvalidStageOperation{} }
func (m *InvalidStageOperation) String() string            { return proto.CompactTextString(m) }
func (*InvalidStageOperation) ProtoMessage()               {}
func (*InvalidStageOperation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *InvalidStageOperation) GetGraphId() string {
	if m != nil {
		return m.GraphId
	}
	return ""
}

func (m *InvalidStageOperation) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *InvalidStageOperation) GetStageId() string {
	if m != nil {
		return m.StageId
	}
	return ""
}

// Invoke commands
type InvokeFunctionRequest struct {
	GraphId    string        `protobuf:"bytes,1,opt,name=graph_id,json=graphId" json:"graph_id,omitempty"`
	StageId    string        `protobuf:"bytes,2,opt,name=stage_id,json=stageId" json:"stage_id,omitempty"`
	FunctionId string        `protobuf:"bytes,3,opt,name=function_id,json=functionId" json:"function_id,omitempty"`
	Arg        *HttpReqDatum `protobuf:"bytes,4,opt,name=arg" json:"arg,omitempty"`
}

func (m *InvokeFunctionRequest) Reset()                    { *m = InvokeFunctionRequest{} }
func (m *InvokeFunctionRequest) String() string            { return proto.CompactTextString(m) }
func (*InvokeFunctionRequest) ProtoMessage()               {}
func (*InvokeFunctionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *InvokeFunctionRequest) GetGraphId() string {
	if m != nil {
		return m.GraphId
	}
	return ""
}

func (m *InvokeFunctionRequest) GetStageId() string {
	if m != nil {
		return m.StageId
	}
	return ""
}

func (m *InvokeFunctionRequest) GetFunctionId() string {
	if m != nil {
		return m.FunctionId
	}
	return ""
}

func (m *InvokeFunctionRequest) GetArg() *HttpReqDatum {
	if m != nil {
		return m.Arg
	}
	return nil
}

type InvokeStageRequest struct {
	GraphId     string              `protobuf:"bytes,1,opt,name=graph_id,json=graphId" json:"graph_id,omitempty"`
	StageId     string              `protobuf:"bytes,2,opt,name=stage_id,json=stageId" json:"stage_id,omitempty"`
	FunctionId  string              `protobuf:"bytes,3,opt,name=function_id,json=functionId" json:"function_id,omitempty"`
	Operation   CompletionOperation `protobuf:"varint,4,opt,name=operation,enum=model.CompletionOperation" json:"operation,omitempty"`
	Args        []*CompletionResult `protobuf:"bytes,5,rep,name=args" json:"args,omitempty"`
	Closure     *BlobDatum          `protobuf:"bytes,6,opt,name=closure" json:"closure,omitempty"`
	Exceptional bool                `protobuf:"varint,7,opt,name=exceptional" json:"exceptional,omitempty"`
}

func (m *InvokeStageRequest) Reset()                    { *m = InvokeStageRequest{} }
func (m *InvokeStageRequest) String() string            { return proto.CompactTextString(m) }
func (*InvokeStageRequest) ProtoMessage()               {}
func (*InvokeStageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *InvokeStageRequest) GetGraphId() string {
	if m != nil {
		return m.GraphId
	}
	return ""
}

func (m *InvokeStageRequest) GetStageId() string {
	if m != nil {
		return m.StageId
	}
	return ""
}

func (m *InvokeStageRequest) GetFunctionId() string {
	if m != nil {
		return m.FunctionId
	}
	return ""
}

func (m *InvokeStageRequest) GetOperation() CompletionOperation {
	if m != nil {
		return m.Operation
	}
	return CompletionOperation_unknown_operation
}

func (m *InvokeStageRequest) GetArgs() []*CompletionResult {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *InvokeStageRequest) GetClosure() *BlobDatum {
	if m != nil {
		return m.Closure
	}
	return nil
}

func (m *InvokeStageRequest) GetExceptional() bool {
	if m != nil {
		return m.Exceptional
	}
	return false
}

type DelayScheduledEvent struct {
	StageId string                     `protobuf:"bytes,1,opt,name=stage_id,json=stageId" json:"stage_id,omitempty"`
	TimeMs  int64                      `protobuf:"varint,2,opt,name=time_ms,json=timeMs" json:"time_ms,omitempty"`
	Ts      *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=ts" json:"ts,omitempty"`
}

func (m *DelayScheduledEvent) Reset()                    { *m = DelayScheduledEvent{} }
func (m *DelayScheduledEvent) String() string            { return proto.CompactTextString(m) }
func (*DelayScheduledEvent) ProtoMessage()               {}
func (*DelayScheduledEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *DelayScheduledEvent) GetStageId() string {
	if m != nil {
		return m.StageId
	}
	return ""
}

func (m *DelayScheduledEvent) GetTimeMs() int64 {
	if m != nil {
		return m.TimeMs
	}
	return 0
}

func (m *DelayScheduledEvent) GetTs() *google_protobuf.Timestamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

type GraphCreatedEvent struct {
	GraphId    string                     `protobuf:"bytes,1,opt,name=graph_id,json=graphId" json:"graph_id,omitempty"`
	FunctionId string                     `protobuf:"bytes,2,opt,name=function_id,json=functionId" json:"function_id,omitempty"`
	Ts         *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=ts" json:"ts,omitempty"`
}

func (m *GraphCreatedEvent) Reset()                    { *m = GraphCreatedEvent{} }
func (m *GraphCreatedEvent) String() string            { return proto.CompactTextString(m) }
func (*GraphCreatedEvent) ProtoMessage()               {}
func (*GraphCreatedEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *GraphCreatedEvent) GetGraphId() string {
	if m != nil {
		return m.GraphId
	}
	return ""
}

func (m *GraphCreatedEvent) GetFunctionId() string {
	if m != nil {
		return m.FunctionId
	}
	return ""
}

func (m *GraphCreatedEvent) GetTs() *google_protobuf.Timestamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

type GraphCompletedEvent struct {
	GraphId    string                     `protobuf:"bytes,1,opt,name=graph_id,json=graphId" json:"graph_id,omitempty"`
	FunctionId string                     `protobuf:"bytes,2,opt,name=function_id,json=functionId" json:"function_id,omitempty"`
	Ts         *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=ts" json:"ts,omitempty"`
}

func (m *GraphCompletedEvent) Reset()                    { *m = GraphCompletedEvent{} }
func (m *GraphCompletedEvent) String() string            { return proto.CompactTextString(m) }
func (*GraphCompletedEvent) ProtoMessage()               {}
func (*GraphCompletedEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

func (m *GraphCompletedEvent) GetGraphId() string {
	if m != nil {
		return m.GraphId
	}
	return ""
}

func (m *GraphCompletedEvent) GetFunctionId() string {
	if m != nil {
		return m.FunctionId
	}
	return ""
}

func (m *GraphCompletedEvent) GetTs() *google_protobuf.Timestamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

type GraphCommittedEvent struct {
	GraphId string                     `protobuf:"bytes,1,opt,name=graph_id,json=graphId" json:"graph_id,omitempty"`
	Ts      *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=ts" json:"ts,omitempty"`
}

func (m *GraphCommittedEvent) Reset()                    { *m = GraphCommittedEvent{} }
func (m *GraphCommittedEvent) String() string            { return proto.CompactTextString(m) }
func (*GraphCommittedEvent) ProtoMessage()               {}
func (*GraphCommittedEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

func (m *GraphCommittedEvent) GetGraphId() string {
	if m != nil {
		return m.GraphId
	}
	return ""
}

func (m *GraphCommittedEvent) GetTs() *google_protobuf.Timestamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

type StageAddedEvent struct {
	StageId      string                     `protobuf:"bytes,1,opt,name=stage_id,json=stageId" json:"stage_id,omitempty"`
	Op           CompletionOperation        `protobuf:"varint,2,opt,name=op,enum=model.CompletionOperation" json:"op,omitempty"`
	Closure      *BlobDatum                 `protobuf:"bytes,3,opt,name=closure" json:"closure,omitempty"`
	Dependencies []string                   `protobuf:"bytes,4,rep,name=dependencies" json:"dependencies,omitempty"`
	Ts           *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=ts" json:"ts,omitempty"`
	CreatorId    string                     `protobuf:"bytes,6,opt,name=creator_id,json=creatorId" json:"creator_id,omitempty"`
}

func (m *StageAddedEvent) Reset()                    { *m = StageAddedEvent{} }
func (m *StageAddedEvent) String() string            { return proto.CompactTextString(m) }
func (*StageAddedEvent) ProtoMessage()               {}
func (*StageAddedEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{39} }

func (m *StageAddedEvent) GetStageId() string {
	if m != nil {
		return m.StageId
	}
	return ""
}

func (m *StageAddedEvent) GetOp() CompletionOperation {
	if m != nil {
		return m.Op
	}
	return CompletionOperation_unknown_operation
}

func (m *StageAddedEvent) GetClosure() *BlobDatum {
	if m != nil {
		return m.Closure
	}
	return nil
}

func (m *StageAddedEvent) GetDependencies() []string {
	if m != nil {
		return m.Dependencies
	}
	return nil
}

func (m *StageAddedEvent) GetTs() *google_protobuf.Timestamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

func (m *StageAddedEvent) GetCreatorId() string {
	if m != nil {
		return m.CreatorId
	}
	return ""
}

type StageCompletedEvent struct {
	StageId string                     `protobuf:"bytes,1,opt,name=stage_id,json=stageId" json:"stage_id,omitempty"`
	Result  *CompletionResult          `protobuf:"bytes,2,opt,name=result" json:"result,omitempty"`
	Ts      *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=ts" json:"ts,omitempty"`
}

func (m *StageCompletedEvent) Reset()                    { *m = StageCompletedEvent{} }
func (m *StageCompletedEvent) String() string            { return proto.CompactTextString(m) }
func (*StageCompletedEvent) ProtoMessage()               {}
func (*StageCompletedEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{40} }

func (m *StageCompletedEvent) GetStageId() string {
	if m != nil {
		return m.StageId
	}
	return ""
}

func (m *StageCompletedEvent) GetResult() *CompletionResult {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *StageCompletedEvent) GetTs() *google_protobuf.Timestamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

type StageComposedEvent struct {
	StageId         string                     `protobuf:"bytes,1,opt,name=stage_id,json=stageId" json:"stage_id,omitempty"`
	ComposedStageId string                     `protobuf:"bytes,2,opt,name=composed_stage_id,json=composedStageId" json:"composed_stage_id,omitempty"`
	Ts              *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=ts" json:"ts,omitempty"`
}

func (m *StageComposedEvent) Reset()                    { *m = StageComposedEvent{} }
func (m *StageComposedEvent) String() string            { return proto.CompactTextString(m) }
func (*StageComposedEvent) ProtoMessage()               {}
func (*StageComposedEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{41} }

func (m *StageComposedEvent) GetStageId() string {
	if m != nil {
		return m.StageId
	}
	return ""
}

func (m *StageComposedEvent) GetComposedStageId() string {
	if m != nil {
		return m.ComposedStageId
	}
	return ""
}

func (m *StageComposedEvent) GetTs() *google_protobuf.Timestamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

type FaasInvocationStartedEvent struct {
	StageId string                     `protobuf:"bytes,1,opt,name=stage_id,json=stageId" json:"stage_id,omitempty"`
	Ts      *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=ts" json:"ts,omitempty"`
}

func (m *FaasInvocationStartedEvent) Reset()                    { *m = FaasInvocationStartedEvent{} }
func (m *FaasInvocationStartedEvent) String() string            { return proto.CompactTextString(m) }
func (*FaasInvocationStartedEvent) ProtoMessage()               {}
func (*FaasInvocationStartedEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{42} }

func (m *FaasInvocationStartedEvent) GetStageId() string {
	if m != nil {
		return m.StageId
	}
	return ""
}

func (m *FaasInvocationStartedEvent) GetTs() *google_protobuf.Timestamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

type FaasInvocationCompletedEvent struct {
	StageId string                     `protobuf:"bytes,1,opt,name=stage_id,json=stageId" json:"stage_id,omitempty"`
	Result  *CompletionResult          `protobuf:"bytes,2,opt,name=result" json:"result,omitempty"`
	Ts      *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=ts" json:"ts,omitempty"`
}

func (m *FaasInvocationCompletedEvent) Reset()                    { *m = FaasInvocationCompletedEvent{} }
func (m *FaasInvocationCompletedEvent) String() string            { return proto.CompactTextString(m) }
func (*FaasInvocationCompletedEvent) ProtoMessage()               {}
func (*FaasInvocationCompletedEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{43} }

func (m *FaasInvocationCompletedEvent) GetStageId() string {
	if m != nil {
		return m.StageId
	}
	return ""
}

func (m *FaasInvocationCompletedEvent) GetResult() *CompletionResult {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *FaasInvocationCompletedEvent) GetTs() *google_protobuf.Timestamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

func init() {
	proto.RegisterType((*CompletionResult)(nil), "model.CompletionResult")
	proto.RegisterType((*BlobDatum)(nil), "model.BlobDatum")
	proto.RegisterType((*HttpHeader)(nil), "model.HttpHeader")
	proto.RegisterType((*HttpReqDatum)(nil), "model.HttpReqDatum")
	proto.RegisterType((*HttpRespDatum)(nil), "model.HttpRespDatum")
	proto.RegisterType((*EmptyDatum)(nil), "model.EmptyDatum")
	proto.RegisterType((*StageRefDatum)(nil), "model.StageRefDatum")
	proto.RegisterType((*ErrorDatum)(nil), "model.ErrorDatum")
	proto.RegisterType((*Datum)(nil), "model.Datum")
	proto.RegisterType((*AddChainedStageRequest)(nil), "model.AddChainedStageRequest")
	proto.RegisterType((*AddCompletedValueStageRequest)(nil), "model.AddCompletedValueStageRequest")
	proto.RegisterType((*AddDelayStageRequest)(nil), "model.AddDelayStageRequest")
	proto.RegisterType((*AddExternalCompletionStageRequest)(nil), "model.AddExternalCompletionStageRequest")
	proto.RegisterType((*AddInvokeFunctionStageRequest)(nil), "model.AddInvokeFunctionStageRequest")
	proto.RegisterType((*AddStageResponse)(nil), "model.AddStageResponse")
	proto.RegisterType((*CommitGraphRequest)(nil), "model.CommitGraphRequest")
	proto.RegisterType((*CommitGraphProcessed)(nil), "model.CommitGraphProcessed")
	proto.RegisterType((*CompleteDelayStageRequest)(nil), "model.CompleteDelayStageRequest")
	proto.RegisterType((*CompleteStageExternallyRequest)(nil), "model.CompleteStageExternallyRequest")
	proto.RegisterType((*CompleteStageExternallyResponse)(nil), "model.CompleteStageExternallyResponse")
	proto.RegisterType((*DeactivateGraphRequest)(nil), "model.DeactivateGraphRequest")
	proto.RegisterType((*CreateGraphRequest)(nil), "model.CreateGraphRequest")
	proto.RegisterType((*CreateGraphResponse)(nil), "model.CreateGraphResponse")
	proto.RegisterType((*FaasInvocationResponse)(nil), "model.FaasInvocationResponse")
	proto.RegisterType((*GetGraphStateRequest)(nil), "model.GetGraphStateRequest")
	proto.RegisterType((*GetGraphStateResponse)(nil), "model.GetGraphStateResponse")
	proto.RegisterType((*GetGraphStateResponse_StageRepresentation)(nil), "model.GetGraphStateResponse.StageRepresentation")
	proto.RegisterType((*ListGraphsRequest)(nil), "model.ListGraphsRequest")
	proto.RegisterType((*ListGraphResponse)(nil), "model.ListGraphResponse")
	proto.RegisterType((*ListGraphsResponse)(nil), "model.ListGraphsResponse")
	proto.RegisterType((*GetStageResultRequest)(nil), "model.GetStageResultRequest")
	proto.RegisterType((*GetStageResultResponse)(nil), "model.GetStageResultResponse")
	proto.RegisterType((*InvalidGraphOperation)(nil), "model.InvalidGraphOperation")
	proto.RegisterType((*InvalidStageOperation)(nil), "model.InvalidStageOperation")
	proto.RegisterType((*InvokeFunctionRequest)(nil), "model.InvokeFunctionRequest")
	proto.RegisterType((*InvokeStageRequest)(nil), "model.InvokeStageRequest")
	proto.RegisterType((*DelayScheduledEvent)(nil), "model.DelayScheduledEvent")
	proto.RegisterType((*GraphCreatedEvent)(nil), "model.GraphCreatedEvent")
	proto.RegisterType((*GraphCompletedEvent)(nil), "model.GraphCompletedEvent")
	proto.RegisterType((*GraphCommittedEvent)(nil), "model.GraphCommittedEvent")
	proto.RegisterType((*StageAddedEvent)(nil), "model.StageAddedEvent")
	proto.RegisterType((*StageCompletedEvent)(nil), "model.StageCompletedEvent")
	proto.RegisterType((*StageComposedEvent)(nil), "model.StageComposedEvent")
	proto.RegisterType((*FaasInvocationStartedEvent)(nil), "model.FaasInvocationStartedEvent")
	proto.RegisterType((*FaasInvocationCompletedEvent)(nil), "model.FaasInvocationCompletedEvent")
	proto.RegisterEnum("model.HttpMethod", HttpMethod_name, HttpMethod_value)
	proto.RegisterEnum("model.ErrorDatumType", ErrorDatumType_name, ErrorDatumType_value)
	proto.RegisterEnum("model.CompletionOperation", CompletionOperation_name, CompletionOperation_value)
	proto.RegisterEnum("model.ListGraphsFilter", ListGraphsFilter_name, ListGraphsFilter_value)
}

func init() { proto.RegisterFile("model.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1780 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0xcd, 0x6f, 0x1c, 0x49,
	0x15, 0x77, 0x4f, 0xf7, 0xcc, 0x78, 0xde, 0xd8, 0x4e, 0xb9, 0xec, 0x38, 0x13, 0xc3, 0x6e, 0xbc,
	0x2d, 0x40, 0x5e, 0x2f, 0xb2, 0xb3, 0x0e, 0x87, 0x15, 0x27, 0x1c, 0x7f, 0xac, 0x2d, 0x11, 0x65,
	0xe9, 0x44, 0x7b, 0x02, 0x8d, 0xca, 0x5d, 0x35, 0x33, 0x8d, 0x7b, 0xba, 0x3b, 0x5d, 0xd5, 0xce,
	0x8e, 0x10, 0x42, 0x82, 0xc3, 0x4a, 0x08, 0x8e, 0x70, 0x5e, 0x2e, 0x88, 0x3f, 0x86, 0x0b, 0x7f,
	0x06, 0x67, 0xfe, 0x01, 0x54, 0x1f, 0x3d, 0xfd, 0xe1, 0x24, 0xd3, 0x5e, 0x43, 0xb4, 0xb7, 0xae,
	0x57, 0xbf, 0x7a, 0xef, 0xf7, 0x3e, 0xaa, 0xea, 0x75, 0x41, 0x7f, 0x1a, 0x53, 0x16, 0xee, 0x27,
	0x69, 0x2c, 0x62, 0xdc, 0x56, 0x83, 0xed, 0x47, 0xe3, 0x38, 0x1e, 0x87, 0xec, 0x40, 0x09, 0x2f,
	0xb3, 0xd1, 0x81, 0x08, 0xa6, 0x8c, 0x0b, 0x32, 0x4d, 0x34, 0xce, 0xfd, 0x12, 0xd0, 0x71, 0x3c,
	0x4d, 0x42, 0x26, 0x82, 0x38, 0xf2, 0x18, 0xcf, 0x42, 0x81, 0x3f, 0x04, 0xe0, 0x99, 0xef, 0x33,
	0xce, 0x47, 0x59, 0x38, 0xb0, 0x76, 0xac, 0xdd, 0x65, 0xaf, 0x24, 0xc1, 0x2e, 0xb4, 0x29, 0x11,
	0xd9, 0x74, 0xd0, 0xda, 0xb1, 0x76, 0xfb, 0x87, 0x2b, 0xfb, 0xda, 0xf0, 0x89, 0x94, 0x79, 0x7a,
	0xca, 0x1d, 0x42, 0xef, 0x69, 0x18, 0x5f, 0x2a, 0x19, 0x7e, 0x00, 0xdd, 0xcb, 0x30, 0xbe, 0x1c,
	0x06, 0x54, 0x69, 0xeb, 0x79, 0x1d, 0x39, 0xbc, 0xa0, 0xf8, 0x23, 0x58, 0xf1, 0xe3, 0x48, 0xb0,
	0x48, 0x0c, 0xc5, 0x2c, 0x61, 0x4a, 0x61, 0xcf, 0xeb, 0x1b, 0xd9, 0xcb, 0x59, 0xc2, 0xf0, 0x16,
	0x74, 0x42, 0x16, 0x8d, 0xc5, 0x64, 0x60, 0xef, 0x58, 0xbb, 0x8e, 0x67, 0x46, 0xee, 0x4f, 0x00,
	0xce, 0x85, 0x48, 0xce, 0x19, 0xa1, 0x2c, 0xc5, 0x08, 0xec, 0x2b, 0x36, 0x33, 0xda, 0xe5, 0x27,
	0xde, 0x84, 0xf6, 0x35, 0x09, 0xb3, 0x5c, 0xa7, 0x1e, 0xb8, 0x7f, 0xb2, 0x60, 0x45, 0x2e, 0xf3,
	0xd8, 0x2b, 0x4d, 0xed, 0x07, 0xe0, 0x5c, 0xc6, 0x54, 0xaf, 0xec, 0x1f, 0x22, 0xe3, 0xca, 0x9c,
	0xba, 0xa7, 0x66, 0xf1, 0x27, 0xd0, 0x9d, 0x28, 0x43, 0x7c, 0x60, 0xef, 0xd8, 0xbb, 0xfd, 0xc3,
	0x75, 0x03, 0x2c, 0x28, 0x78, 0x39, 0x02, 0x7f, 0x0c, 0x9d, 0x29, 0x13, 0x93, 0x98, 0x0e, 0x9c,
	0x1d, 0x6b, 0x77, 0xad, 0x82, 0x7d, 0xa6, 0x26, 0x3c, 0x03, 0x70, 0xff, 0x60, 0xc1, 0xaa, 0xa6,
	0xc3, 0x93, 0xff, 0x1b, 0x9f, 0x47, 0xd0, 0xe7, 0x82, 0x88, 0x8c, 0x0f, 0xfd, 0x98, 0x32, 0x45,
	0x6a, 0xd5, 0x03, 0x2d, 0x3a, 0x8e, 0x29, 0x73, 0x57, 0x00, 0x4e, 0xa7, 0x89, 0x98, 0x29, 0x0b,
	0xee, 0x8f, 0x61, 0xf5, 0x85, 0x20, 0x63, 0xe6, 0xb1, 0x91, 0xa6, 0xf4, 0x3d, 0xe8, 0x71, 0x29,
	0x18, 0xa6, 0x6c, 0x64, 0x22, 0xbc, 0xcc, 0x0d, 0xc2, 0xfd, 0x05, 0xc0, 0x69, 0x9a, 0xc6, 0xa9,
	0x86, 0x7e, 0x0c, 0x8e, 0xca, 0xa3, 0xa5, 0x1c, 0xbf, 0x6f, 0x48, 0x15, 0x00, 0x99, 0x51, 0x4f,
	0x41, 0xf0, 0x00, 0xba, 0x53, 0xc6, 0x39, 0x19, 0xe7, 0x19, 0xca, 0x87, 0xee, 0x3f, 0x5a, 0xd0,
	0xce, 0xd5, 0xb5, 0x99, 0x24, 0x66, 0xa2, 0x91, 0x3b, 0x59, 0x90, 0x3d, 0x5f, 0xf2, 0x34, 0x02,
	0xff, 0x08, 0x1c, 0x59, 0x53, 0xa6, 0x24, 0x6f, 0xc4, 0xed, 0x7c, 0xc9, 0x53, 0xf3, 0x4a, 0xa5,
	0xa4, 0xa3, 0xaa, 0xa9, 0xa4, 0x72, 0x4e, 0x51, 0xa9, 0x94, 0x23, 0xfc, 0xa4, 0xec, 0xb7, 0xa3,
	0xe0, 0x9b, 0x06, 0x5e, 0x09, 0xd0, 0xf9, 0x52, 0x11, 0x0f, 0xfc, 0x18, 0x96, 0x27, 0x42, 0x24,
	0xc3, 0x94, 0xbd, 0x1a, 0xb4, 0xd5, 0x9a, 0x8d, 0x52, 0x6a, 0xf2, 0xb2, 0x3b, 0x5f, 0xf2, 0xba,
	0x13, 0x3d, 0x96, 0x66, 0xcc, 0x0a, 0x9e, 0x0c, 0x3a, 0x15, 0x33, 0x95, 0xd2, 0x90, 0x66, 0x26,
	0x46, 0xf0, 0xb4, 0x0d, 0xf6, 0x35, 0x09, 0xdd, 0x7f, 0x5a, 0xb0, 0x75, 0x44, 0xe9, 0xf1, 0x84,
	0x04, 0x11, 0xa3, 0x86, 0xd5, 0xab, 0x8c, 0x71, 0x81, 0x1f, 0xc2, 0xf2, 0x38, 0x25, 0xc9, 0xa4,
	0xd8, 0x74, 0x5d, 0x35, 0xbe, 0xa0, 0xf8, 0x33, 0xe8, 0xc5, 0x09, 0x4b, 0x89, 0xdc, 0xf2, 0x2a,
	0x60, 0x6b, 0x87, 0xdb, 0xc6, 0x62, 0x71, 0x16, 0x3c, 0xcf, 0x11, 0x5e, 0x01, 0xc6, 0x7b, 0xd0,
	0xf5, 0xc3, 0x98, 0x67, 0x29, 0x33, 0xf1, 0xbb, 0x59, 0xa0, 0x39, 0x00, 0x63, 0x70, 0x28, 0x4b,
	0xf8, 0xc0, 0xd9, 0xb1, 0x77, 0x7b, 0x9e, 0xfa, 0xc6, 0x1f, 0x00, 0xf8, 0x29, 0x23, 0x22, 0x4e,
	0x25, 0xad, 0xb6, 0xa2, 0xd5, 0x33, 0x92, 0x0b, 0xea, 0xfe, 0xd1, 0x82, 0x0f, 0xa4, 0x3b, 0x9a,
	0x04, 0xa3, 0x5f, 0xca, 0x3d, 0xdb, 0xd4, 0xab, 0x03, 0xe8, 0xa4, 0xea, 0xfc, 0x32, 0x35, 0xf0,
	0xe0, 0x86, 0x4b, 0xfa, 0x78, 0xf3, 0x0c, 0xac, 0x46, 0xc6, 0xae, 0x93, 0xb9, 0x82, 0xcd, 0x23,
	0x4a, 0x4f, 0x58, 0x48, 0x66, 0x4d, 0x29, 0x3c, 0x84, 0x65, 0x2a, 0xf1, 0xc3, 0x29, 0x57, 0x24,
	0x6c, 0xaf, 0xab, 0xc6, 0xcf, 0xf8, 0x22, 0x63, 0xbf, 0x82, 0x8f, 0x8e, 0x28, 0x3d, 0xfd, 0x4a,
	0xb0, 0x34, 0x22, 0x61, 0x41, 0xb9, 0xa9, 0xe5, 0xaa, 0xfa, 0x56, 0x5d, 0xfd, 0xdf, 0x74, 0x60,
	0x2f, 0xa2, 0xeb, 0xf8, 0x8a, 0x9d, 0x65, 0x91, 0x7f, 0x1b, 0xdd, 0x8f, 0xa0, 0x3f, 0x32, 0x4b,
	0x0a, 0xe5, 0x90, 0x8b, 0x2e, 0x28, 0xfe, 0x21, 0xd8, 0x24, 0x1d, 0x9b, 0x8a, 0x78, 0x53, 0xb9,
	0x7b, 0x72, 0xbe, 0xc6, 0xd1, 0xa9, 0x73, 0x3c, 0x07, 0x74, 0x44, 0xf3, 0x1a, 0xe6, 0x49, 0x1c,
	0x71, 0xb6, 0x20, 0xd6, 0x7a, 0x77, 0xce, 0x29, 0x75, 0xd5, 0xf8, 0x82, 0xba, 0x07, 0x80, 0x8f,
	0xe3, 0xe9, 0x34, 0x10, 0x9f, 0x4b, 0xec, 0x62, 0x0f, 0xdd, 0x4f, 0x61, 0xb3, 0xb4, 0xe0, 0x8b,
	0x34, 0x96, 0x37, 0x1d, 0xa3, 0xef, 0x5a, 0xf2, 0x7b, 0x0b, 0x1e, 0xe6, 0x75, 0x7a, 0xdb, 0x1a,
	0x79, 0x0b, 0xef, 0x52, 0x05, 0xdb, 0x8d, 0x2a, 0xd8, 0xfd, 0xda, 0x82, 0x0f, 0x73, 0x12, 0xca,
	0x7e, 0x5e, 0x40, 0xe1, 0xec, 0x3d, 0x33, 0x79, 0x0d, 0x8f, 0xde, 0x4a, 0xe4, 0x2e, 0xb9, 0xac,
	0xf5, 0x22, 0x76, 0xbd, 0x17, 0x71, 0x9f, 0xc0, 0xd6, 0x09, 0x23, 0xbe, 0x08, 0xae, 0x89, 0x60,
	0x4d, 0xf3, 0xfd, 0x05, 0xe0, 0x63, 0x59, 0x77, 0xd5, 0x05, 0xb5, 0x3a, 0xb7, 0x6e, 0xd4, 0x79,
	0x59, 0x63, 0xab, 0xaa, 0xf1, 0x31, 0x6c, 0x54, 0x34, 0x2e, 0xf4, 0xd9, 0xfd, 0xc6, 0x82, 0xad,
	0x33, 0x42, 0xb8, 0xdc, 0x93, 0x3e, 0x31, 0x21, 0xbd, 0x4b, 0xa4, 0x6a, 0xf4, 0xed, 0x1b, 0xf4,
	0x8b, 0xa4, 0x3a, 0xcd, 0x92, 0xfa, 0x29, 0x6c, 0x7e, 0xce, 0xf4, 0x9e, 0x78, 0x21, 0x88, 0x68,
	0x50, 0xdd, 0xee, 0xbf, 0x5b, 0x70, 0xbf, 0xb6, 0xc6, 0x38, 0xf5, 0x33, 0xe8, 0x28, 0xa6, 0x7c,
	0x60, 0xa9, 0x8e, 0x65, 0xd7, 0x58, 0x7f, 0x23, 0x5a, 0x5f, 0xb0, 0xfc, 0x34, 0x12, 0xe9, 0xcc,
	0x33, 0xeb, 0x16, 0x9f, 0x43, 0x65, 0x5e, 0x76, 0x85, 0xd7, 0x36, 0x83, 0x0d, 0xb3, 0x41, 0x93,
	0x94, 0x71, 0x16, 0x09, 0x7d, 0x9f, 0xe1, 0x52, 0xbf, 0xd2, 0x33, 0x8d, 0xc9, 0x96, 0x22, 0x2a,
	0x32, 0x6e, 0x2c, 0x98, 0x11, 0x76, 0x61, 0x85, 0xb2, 0x84, 0x45, 0x94, 0x45, 0x7e, 0xc0, 0x74,
	0xe3, 0xd5, 0xf3, 0x2a, 0xb2, 0xed, 0x2b, 0xe8, 0x97, 0x98, 0xbf, 0xa1, 0x2b, 0x3d, 0x2b, 0x77,
	0xa5, 0xfd, 0xc3, 0xc7, 0x8b, 0x83, 0x50, 0x65, 0x6c, 0xfa, 0xd8, 0x9f, 0xb6, 0x3e, 0xb3, 0xdc,
	0x13, 0x58, 0xff, 0x79, 0xc0, 0xf5, 0x42, 0x9e, 0xe7, 0xe6, 0x00, 0x3a, 0xa3, 0x20, 0x14, 0x2c,
	0x35, 0x3d, 0x58, 0x9e, 0xe4, 0x02, 0x79, 0xa6, 0xa6, 0x3d, 0x03, 0x73, 0xf7, 0x4b, 0x5a, 0x9a,
	0xd4, 0xed, 0x19, 0xe0, 0xb2, 0x55, 0xb3, 0xe0, 0x31, 0x74, 0x14, 0x20, 0xcf, 0xee, 0xa0, 0x6e,
	0x36, 0x47, 0x7a, 0x06, 0xe7, 0x3e, 0x53, 0x85, 0x92, 0x1f, 0xf7, 0xb2, 0xec, 0xee, 0x72, 0x62,
	0xb9, 0xbf, 0x83, 0xad, 0xba, 0xba, 0x3b, 0xed, 0xa6, 0x5b, 0x9f, 0x80, 0x27, 0x70, 0xff, 0x22,
	0xba, 0x26, 0x61, 0x40, 0x95, 0xbf, 0xf3, 0xf6, 0xe9, 0x5d, 0xf6, 0x11, 0xd8, 0x2c, 0x4d, 0x8d,
	0x69, 0xf9, 0xe9, 0x0e, 0xe7, 0x5a, 0x94, 0x2b, 0xdf, 0x4e, 0x4b, 0xc5, 0x2f, 0xbb, 0x1a, 0xa7,
	0xbf, 0x58, 0xca, 0x42, 0xa9, 0x0d, 0xb8, 0xdb, 0x4d, 0xb1, 0xf0, 0xd4, 0x31, 0xcd, 0x81, 0xf3,
	0xee, 0xe6, 0xc0, 0xfd, 0xa6, 0x05, 0x58, 0xf3, 0xfa, 0x1f, 0x5c, 0xa4, 0x0b, 0x49, 0x55, 0x3a,
	0x60, 0xe7, 0x36, 0x1d, 0xf0, 0x27, 0xe0, 0x90, 0x74, 0xcc, 0x07, 0x6d, 0x55, 0xe6, 0x6f, 0xad,
	0x0a, 0x05, 0x2a, 0xb7, 0xcb, 0x9d, 0x45, 0xed, 0xf2, 0x0e, 0xf4, 0xd9, 0x57, 0x3e, 0x4b, 0xa4,
	0x12, 0x12, 0x0e, 0xba, 0xea, 0xa6, 0x2b, 0x8b, 0xdc, 0x0c, 0x36, 0x74, 0xa7, 0xe1, 0x4f, 0x18,
	0xcd, 0x42, 0x46, 0x4f, 0xaf, 0x59, 0x24, 0x2a, 0x71, 0xb0, 0xaa, 0x71, 0x78, 0x00, 0x5d, 0xf9,
	0xbf, 0x5f, 0xb4, 0xa3, 0x1d, 0x39, 0x7c, 0x26, 0x89, 0xb5, 0x04, 0x37, 0x95, 0xbd, 0xbd, 0xaf,
	0xdf, 0x08, 0xf6, 0xf3, 0x37, 0x82, 0xfd, 0x97, 0xf9, 0x1b, 0x81, 0xd7, 0x12, 0xdc, 0xfd, 0x0d,
	0xac, 0xab, 0x8a, 0xd6, 0xf7, 0x5b, 0x61, 0xf4, 0x5b, 0xb7, 0x8b, 0xb7, 0x31, 0xfe, 0x5b, 0xd8,
	0xd0, 0xc6, 0xf3, 0x5f, 0x82, 0xf7, 0x6b, 0xfe, 0x97, 0x85, 0xf9, 0x69, 0x20, 0x9a, 0x98, 0xd7,
	0xda, 0x5b, 0x8d, 0xb4, 0xff, 0xc7, 0x82, 0x7b, 0xaa, 0xda, 0x8f, 0x28, 0x6d, 0x90, 0xcd, 0x3d,
	0x68, 0xc5, 0x49, 0x83, 0xff, 0xb5, 0x56, 0x9c, 0xdc, 0xea, 0x47, 0xad, 0x7e, 0xb1, 0x39, 0x37,
	0x2f, 0x36, 0xe3, 0x56, 0xbb, 0x89, 0x5b, 0xb5, 0x3e, 0xbf, 0x53, 0xef, 0xf3, 0xff, 0x6c, 0x99,
	0xbb, 0xf8, 0x66, 0x4e, 0xdf, 0xe6, 0xf9, 0xad, 0x7f, 0xed, 0x6e, 0x93, 0xe3, 0xaf, 0x2d, 0xc0,
	0x73, 0x3e, 0x31, 0x6f, 0x94, 0x88, 0x75, 0xdf, 0x60, 0x87, 0xb5, 0x23, 0xe8, 0x5e, 0x3e, 0xf1,
	0xa2, 0x48, 0x5a, 0x63, 0x26, 0x3e, 0x6c, 0x57, 0x3b, 0xc2, 0x17, 0x82, 0xa4, 0xa2, 0x59, 0x65,
	0x34, 0x2e, 0xba, 0xbf, 0x5a, 0xf0, 0xfd, 0xaa, 0x95, 0xef, 0x46, 0x1e, 0xf6, 0x7e, 0xad, 0x1f,
	0xf4, 0xf4, 0x0b, 0x19, 0xc6, 0xb0, 0x96, 0x45, 0x57, 0x51, 0xfc, 0x3a, 0x1a, 0xea, 0xb7, 0x32,
	0xb4, 0x84, 0xbb, 0x60, 0x8f, 0x99, 0x40, 0x16, 0x5e, 0x06, 0x67, 0xc2, 0x08, 0x45, 0x2d, 0xf9,
	0x95, 0xc4, 0x5c, 0x20, 0x5b, 0x4e, 0x26, 0x99, 0x40, 0x0e, 0x06, 0xe8, 0x50, 0x26, 0xfd, 0x41,
	0x6d, 0xdc, 0x87, 0x6e, 0xac, 0x8e, 0x4f, 0x8e, 0xba, 0xb8, 0x07, 0xed, 0x84, 0x08, 0x7f, 0x82,
	0x3a, 0x7b, 0x7f, 0xb7, 0x60, 0xad, 0xfa, 0x2a, 0x85, 0xd7, 0x61, 0x35, 0x37, 0xa8, 0x9e, 0x7f,
	0xd0, 0x92, 0x14, 0xe9, 0x48, 0xc8, 0x53, 0x33, 0xce, 0xa4, 0x65, 0x04, 0x2b, 0x5a, 0x34, 0x22,
	0x41, 0xc8, 0x24, 0x83, 0x4d, 0x40, 0xf3, 0xf3, 0x26, 0xc7, 0xd9, 0x78, 0x1b, 0xb6, 0x8a, 0x53,
	0x48, 0x5d, 0x6b, 0xf9, 0x0a, 0x07, 0xaf, 0x01, 0x68, 0x1d, 0xa1, 0x64, 0xde, 0x96, 0xd8, 0x40,
	0xdf, 0xf9, 0xc3, 0xfc, 0xbd, 0x49, 0xb7, 0x2e, 0xa8, 0xb3, 0xf7, 0xaf, 0x16, 0x6c, 0xbc, 0x61,
	0x8f, 0xe3, 0xfb, 0xb0, 0x9e, 0xb3, 0x9d, 0xdf, 0x4d, 0x68, 0x49, 0xd2, 0x23, 0xbe, 0xbc, 0x31,
	0x4e, 0x03, 0x31, 0x61, 0x29, 0xb2, 0xa4, 0x0f, 0x24, 0x49, 0xc2, 0xd9, 0xcb, 0xd8, 0x88, 0x5a,
	0x32, 0xb4, 0x62, 0xc2, 0xa2, 0x23, 0x05, 0x7c, 0x1a, 0x8b, 0x09, 0xb2, 0xf1, 0x2a, 0xf4, 0x94,
	0x4c, 0x42, 0x91, 0x23, 0xe3, 0x26, 0x87, 0x5e, 0x16, 0xa1, 0xb6, 0xe4, 0x5b, 0xe0, 0x51, 0x07,
	0xdf, 0x83, 0xbe, 0x1c, 0x9b, 0xed, 0x82, 0xba, 0x25, 0xc1, 0x65, 0x10, 0x31, 0xb4, 0x2c, 0x69,
	0xbc, 0x36, 0x08, 0x95, 0x88, 0x9e, 0x4c, 0xca, 0x84, 0x44, 0x34, 0x64, 0x08, 0xe4, 0x37, 0xcf,
	0x94, 0xa1, 0xbe, 0xe4, 0x12, 0x54, 0xba, 0x11, 0xb4, 0x22, 0x65, 0x7e, 0xe5, 0x05, 0x08, 0xad,
	0xca, 0xdc, 0xa9, 0x97, 0x14, 0xb4, 0x26, 0x3f, 0x49, 0x18, 0x3e, 0x1f, 0xa1, 0x7b, 0xea, 0x33,
	0x9a, 0x3d, 0x1f, 0x21, 0x84, 0xb7, 0x00, 0xb3, 0x1b, 0xaf, 0x27, 0x68, 0x5d, 0xfa, 0x5f, 0xba,
	0x43, 0xc3, 0x19, 0xc2, 0x7b, 0x27, 0x80, 0xea, 0xdd, 0xb0, 0x74, 0xd8, 0xc4, 0x53, 0xd7, 0x19,
	0x09, 0x43, 0x64, 0x49, 0x69, 0x9a, 0x45, 0x51, 0x10, 0x8d, 0x51, 0x4b, 0x86, 0x68, 0x4e, 0x0b,
	0xd9, 0x97, 0x1d, 0x55, 0xc6, 0x4f, 0xfe, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x10, 0x6c, 0x2e,
	0x76, 0x17, 0x00, 0x00,
}
