// Code generated by protoc-gen-go. DO NOT EDIT.
// source: testprotos.proto

/*
Package persistence is a generated protocol buffer package.

It is generated from these files:
	testprotos.proto

It has these top-level messages:
	TestEvent
	TestSnapshot
*/
package persistence

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TestEvent struct {
	Index     uint32 `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	StringVal string `protobuf:"bytes,2,opt,name=string_val,json=stringVal" json:"string_val,omitempty"`
}

func (m *TestEvent) Reset()                    { *m = TestEvent{} }
func (m *TestEvent) String() string            { return proto.CompactTextString(m) }
func (*TestEvent) ProtoMessage()               {}
func (*TestEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TestEvent) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *TestEvent) GetStringVal() string {
	if m != nil {
		return m.StringVal
	}
	return ""
}

type TestSnapshot struct {
	StringVal string `protobuf:"bytes,1,opt,name=string_val,json=stringVal" json:"string_val,omitempty"`
	Index     uint32 `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
}

func (m *TestSnapshot) Reset()                    { *m = TestSnapshot{} }
func (m *TestSnapshot) String() string            { return proto.CompactTextString(m) }
func (*TestSnapshot) ProtoMessage()               {}
func (*TestSnapshot) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TestSnapshot) GetStringVal() string {
	if m != nil {
		return m.StringVal
	}
	return ""
}

func (m *TestSnapshot) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func init() {
	proto.RegisterType((*TestEvent)(nil), "persistence.TestEvent")
	proto.RegisterType((*TestSnapshot)(nil), "persistence.TestSnapshot")
}

func init() { proto.RegisterFile("testprotos.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 139 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x49, 0x2d, 0x2e,
	0x29, 0x28, 0xca, 0x2f, 0xc9, 0x2f, 0xd6, 0x03, 0x53, 0x42, 0xdc, 0x05, 0xa9, 0x45, 0xc5, 0x99,
	0xc5, 0x25, 0xa9, 0x79, 0xc9, 0xa9, 0x4a, 0x0e, 0x5c, 0x9c, 0x21, 0xa9, 0xc5, 0x25, 0xae, 0x65,
	0xa9, 0x79, 0x25, 0x42, 0x22, 0x5c, 0xac, 0x99, 0x79, 0x29, 0xa9, 0x15, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0xbc, 0x41, 0x10, 0x8e, 0x90, 0x2c, 0x17, 0x57, 0x71, 0x49, 0x51, 0x66, 0x5e, 0x7a, 0x7c,
	0x59, 0x62, 0x8e, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x27, 0x44, 0x24, 0x2c, 0x31, 0x47,
	0xc9, 0x99, 0x8b, 0x07, 0x64, 0x42, 0x70, 0x5e, 0x62, 0x41, 0x71, 0x46, 0x7e, 0x09, 0x9a, 0x72,
	0x46, 0x34, 0xe5, 0x08, 0x3b, 0x98, 0x90, 0xec, 0x48, 0x62, 0x03, 0x3b, 0xcd, 0x18, 0x10, 0x00,
	0x00, 0xff, 0xff, 0xec, 0xf7, 0x37, 0xa8, 0xae, 0x00, 0x00, 0x00,
}
